changelog:
  exclude:
    labels:
      - 'skip-changelog'
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking
    - title: New Features 🎉
      labels:
        - feature
    - title: '✨ Design'
      labels:
        - design
    - title: '🚀 New features'
      labels:
        - feature
    - title: '🔧 Maintenance'
      labels:
        - maintenance
    - title: '💯 Improvement'
      labels:
        - improvement
    - title: '📖 Documentation'
      labels:
        - documentation
    - title: '🐛 Bug Fixes'
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
