name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '❌ Breaking'
    label: 'breaking'
  - title: '✨ Design'
    label: 'design'
  - title: '🚀 New features'
    label: 'feature'
  - title: '🔧 Maintenance'
    label: 'maintenance'
  - title: '💯 Improvement'
    label: 'improvement'
  - title: '📖 Documentation'
    label: 'documentation'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '📦 Dependency Updates'
    label: 'depenencies'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'design'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
      - 'improvement'
      - 'depenencies'

exclude-labels:
  - 'skip-changelog'

template: |
  # What's Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
